added initialization steps for simplyblock-csi (#106)
* added initialization steps for simplyblock-csi

* refactor manifest

* fixed installation command

* use case to check linux distro

* remove -q in grep

diff --git a/charts/latest/spdk-csi/templates/node.yaml b/charts/latest/spdk-csi/templates/node.yaml
--- a/charts/latest/spdk-csi/templates/node.yaml
+++ b/charts/latest/spdk-csi/templates/node.yaml
@@ -32,6 +32,47 @@ spec:
         value: {{ .Values.node.tolerations.value }}
         {{- end }}
       {{- end }}
+      initContainers:
+      - name: init-nvme
+        image: "{{ .Values.image.spdkcsi.repository }}:{{ .Values.image.spdkcsi.tag }}"
+        imagePullPolicy: {{ .Values.image.spdkcsi.pullPolicy }}
+        securityContext:
+          privileged: true
+        volumeMounts:
+        - name: host-root
+          mountPath: /host
+        command:
+        - "/bin/sh"
+        - "-c"
+        - |
+          chroot /host /bin/sh -c '
+          . /etc/os-release
+          case "$ID" in
+            ubuntu|debian)
+              INSTALL_CMD="apt-get update && apt-get install -y"
+              ;;
+            centos|rhel|fedora|almalinux|rocky)
+              INSTALL_CMD="dnf install -y"
+              ;;
+            suse|opensuse-leap)
+              INSTALL_CMD="zypper install -y"
+              ;;
+            *)
+              echo "Unsupported Linux distribution: $ID"
+              exit 1
+              ;;
+          esac
+
+          if ! command -v nvme &> /dev/null; then
+            $INSTALL_CMD nvme-cli
+          fi
+
+          if ! lsmod | grep nvme_tcp; then
+            echo "Loading nvme-tcp module..."
+            modprobe nvme-tcp || echo "Failed to load nvme-tcp"
+          else
+            echo "nvme-tcp module is already loaded"
+          fi'
       containers:
       - name: spdkcsi-registrar
         securityContext:
@@ -114,6 +155,9 @@ spec:
       - name: host-sys
         hostPath:
           path: /sys
+      - name: host-root
+        hostPath:
+          path: /
       - name: spdkcsi-nodeserver-config
         configMap:
           name: spdkcsi-nodeservercm
